version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  node: circleci/node@2

jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - add_ssh_keys:
          fingerprints:
            - da:76:8b:64:9e:46:37:92:1c:90:18:ab:c5:90:90:8f
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploying to staging
          command: cap staging deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy
          filters:
            branches:
              only:
                - staging
                # - /rc-.*/
