version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  node: circleci/node@2

jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Deploying
          command: cap staging deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy
