version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  node: circleci/node@2

jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploying to staging
          command: bundle exec cap staging deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy
